config/routes.rb
Rails.application.routes.draw do

  root "pages#home"

  get "secure" => "pages#secure"

  get "/auth/google_oauth2/callback" => "sessions#create"

  delete "/logout" => "sessions#destroy"

end

app/models/user.rb
class User < ActiveRecord::Base

  class << self
    def from_omniauth(auth_hash)
      user = find_or_create_by(uid: auth_hash["uid"], provider: auth_hash['provider'])
      user.name = auth_hash["info"]["name"]
      user.location = auth_hash["info"]["location"]
      user.image_url = auth_hash["info"]["image"]
      user.url = auth_hash["info"]["urls"][user.provider.capitalize]
      user.save!
      user
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  helper_method :current_user

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def secure
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    begin
      @user = User.from_omniauth(request.env["omniauth.auth"])
      session[:user_id] = @user.id
      flash[:success] = "Welcome, #{@user.name}!"
    rescue
      flash[:warning] = "There was an error while trying to authenticate."
    end
    redirect_to root_path
  end

  def destroy
    if current_user
      session.delete(:user_id)
      flash[:success] = "See you later!"
    end
    redirect_to root_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) %> | AuthTest</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-inverse">
  <div class="container">
    <div class="navbar-header">
      <%= link_to "AuthTest", root_path, class: 'navbar-brand' %>
    </div>
    <div id="navbar">
      <% if current_user %>
        <ul class="nav navbar-nav">
          <li><%= image_tag current_user.image_url, alt: current_user.name %></li>
          <li><%= link_to "Log Out", logout_path, method: :delete %></li>
        </ul>
      <% else %>
        <ul class="nav navbar-nav">
          <li><%= link_to "Log in with Google", "/auth/google_oauth2" %></li>
        </ul>
      <% end %>
    </div>
  </div>
</nav>

<div class="container">
  <% flash.each do |key, value| %>
    <div class="alert alert-<%= key %>">
      <%= value %>
    </div>
  <% end %>

  <%= yield %>
</div>
</body>
</html>

app/views/pages/home.html.erb
<% provide(:title, "Home") %>
<% if current_user %>
  <div class="page-header">
    <h1>Here is some info about you...</h1>
  </div>
  <div class="panel panel-default">
    <div class="panel-body">
      <ul>
        <li><strong>Name:</strong> <%= current_user.name %></li>
        <li><strong>Provider:</strong> <%= current_user.provider %></li>
        <li><strong>uID:</strong> <%= current_user.uid %></li>
        <li><strong>Location:</strong> <%= current_user.location %></li>
        <li><strong>Avatar URL:</strong> <%= current_user.image_url %></li>
        <li><strong>URL:</strong> <%= current_user.url %></li>
      </ul>
    </div>
  </div>
<% else %>
  <div class="jumbotron">
    <h1>Welcome!</h1>
    <p><br> Log in with Google above to get started.</p>
  </div>
<% end %>

app/views/pages/secure.html.erb
<h1>Pages#secure</h1>
<p>Find me in app/views/pages/secure.html.erb</p>